apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.secretName" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if not (index .Values "acapy" "argfile.yml" "admin-insecure-mode") }}
  {{- if .Values.acapy.secret.adminApiKey.generated }}
  adminApiKey: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.secretName" .) "Key" "adminApiKey" "Length" 32) }}
  {{ else }}
  adminApiKey: {{ include "common.secrets.lookup" (dict "secret" (include "acapy.secretName" .) "key" "adminApiKey" "defaultValue" .Values.acapy.secret.adminApiKey.value "context" $) }}
  {{- end }}
  {{- end }}
  walletKey: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.secretName" .) "Key" "walletKey" "Length" 32) }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.fullname" . }}
  labels:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  seed: {{ include "acapy.seed" . }}
